/* eslint-disable prettier/prettier */
import Service from '@ember/service';
import { tracked } from '@glimmer/tracking';

export default class StudentDataService extends Service {
    @tracked columns=["S.No","Roll No","Name","Department","DOB","Interests","Address","Action"]
    @tracked students=[
        { id: 1, name: 'Charan', rollno: '21AT1A05E9', dob: '2003-11-17', dept: 'CSE', address: 'Kurnool', interests: ['Coding', 'Cricket', 'Reading'] },
        { id: 2, name: 'Pavan', rollno: '21AT1A05D6', dob: '2002-02-10', dept: 'ECE', address: 'Juturu', interests: ['Football', 'Music', 'Photography'] },
        { id: 3, name: 'Abhi', rollno: '21AT1A05D7', dob: '2002-11-08', dept: 'CSE', address: 'Tadipatri', interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 4, name: 'Rajesh', rollno: '21AT1A05E0', dob: '2002-10-17', dept: 'MECH', address: 'MiryalGuda', interests: ['Chess', 'Dancing', 'Cooking'] },
        { id: 5, name: 'Ganesh', rollno: '21AT1A05E1', dob: '2002-01-11', dept: 'CSE-AI', address: 'Hyderabad', interests: ['AI Research', 'Badminton', 'Painting'] },
        { id: 6, name: 'Prasad', rollno: '21AT1A05E2', dob: '2002-02-19', dept: 'CSE', address: 'Veldurthi', interests: ['Cricket', 'Singing', 'Travel'] },
        { id: 7, name: 'Abdulla', rollno: '21AT1A05F8', dob: '2002-01-15', dept: 'CSE', address: 'Nandikotkur', interests: ['Football', 'Reading', 'Writing'] },
        { id: 8, name: 'Riyaz Shaik', rollno: '21AT1A04H9', dob: '2002-07-01', dept: 'CE', address: 'Nandikotkur', interests: ['Basketball', 'Music', 'Photography'] },
        { id: 9, name: 'Praveen', rollno: '21AT1A0522', dob: '2002-04-22', dept: 'ECE', address: 'Allagadda', interests: ['Volleyball', 'Gaming', 'Cooking'] },
        { id: 10, name: 'Harsha', rollno: '21AT5A04H2', dob: '2002-02-28', dept: 'MECH', address: 'Aluru', interests: ['Cricket', 'Singing', 'Travel'] },
        { id: 11, name: 'Dani', rollno: '21AT1A0479', dob: '2002-11-08', dept: 'CSE', address: 'Tadipatri', interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 12, name: "Student 12", rollno: "21AT1A0012", dob: "2002-01-13", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Music', 'Reading'] },
        { id: 13, name: "Student 13", rollno: "21AT1A0013", dob: "2002-02-14", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Photography'] },
        { id: 14, name: "Student 14", rollno: "21AT1A0014", dob: "2002-03-15", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 15, name: "Student 15", rollno: "21AT1A0015", dob: "2002-04-16", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 16, name: "Student 16", rollno: "21AT1A0016", dob: "2002-05-17", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 17, name: "Student 17", rollno: "21AT1A0017", dob: "2002-06-18", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 18, name: "Student 18", rollno: "21AT1A0018", dob: "2002-07-19", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 19, name: "Student 19", rollno: "21AT1A0019", dob: "2002-08-20", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 20, name: "Student 20", rollno: "21AT1A0020", dob: "2002-09-21", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 21, name: "Student 21", rollno: "21AT1A0021", dob: "2002-10-22", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 22, name: "Student 22", rollno: "21AT1A0022", dob: "2002-11-23", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 23, name: "Student 23", rollno: "21AT1A0023", dob: "2002-12-24", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 24, name: "Student 24", rollno: "21AT1A0024", dob: "2002-01-25", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 25, name: "Student 25", rollno: "21AT1A0025", dob: "2002-02-26", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 26, name: "Student 26", rollno: "21AT1A0026", dob: "2002-03-27", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 27, name: "Student 27", rollno: "21AT1A0027", dob: "2002-04-28", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 28, name: "Student 28", rollno: "21AT1A0028", dob: "2002-05-01", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 29, name: "Student 29", rollno: "21AT1A0029", dob: "2002-06-02", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 30, name: "Student 30", rollno: "21AT1A0030", dob: "2002-07-03", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 31, name: "Student 31", rollno: "21AT1A0031", dob: "2002-08-04", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 32, name: "Student 32", rollno: "21AT1A0032", dob: "2002-09-05", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 33, name: "Student 33", rollno: "21AT1A0033", dob: "2002-10-06", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 34, name: "Student 34", rollno: "21AT1A0034", dob: "2002-11-07", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 35, name: "Student 35", rollno: "21AT1A0035", dob: "2002-12-08", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 36, name: "Student 36", rollno: "21AT1A0036", dob: "2002-01-09", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 37, name: "Student 37", rollno: "21AT1A0037", dob: "2002-02-10", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 38, name: "Student 38", rollno: "21AT1A0038", dob: "2002-03-11", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 39, name: "Student 39", rollno: "21AT1A0039", dob: "2002-04-12", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 40, name: "Student 40", rollno: "21AT1A0040", dob: "2002-05-13", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 41, name: "Student 41", rollno: "21AT1A0041", dob: "2002-06-14", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 42, name: "Student 42", rollno: "21AT1A0042", dob: "2002-07-15", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 43, name: "Student 43", rollno: "21AT1A0043", dob: "2002-08-16", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 44, name: "Student 44", rollno: "21AT1A0044", dob: "2002-09-17", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 45, name: "Student 45", rollno: "21AT1A0045", dob: "2002-10-18", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 46, name: "Student 46", rollno: "21AT1A0046", dob: "2002-11-19", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 47, name: "Student 47", rollno: "21AT1A0047", dob: "2002-12-20", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 48, name: "Student 48", rollno: "21AT1A0048", dob: "2002-01-21", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 49, name: "Student 49", rollno: "21AT1A0049", dob: "2002-02-22", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 50, name: "Student 50", rollno: "21AT1A0050", dob: "2002-03-23", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 51, name: "Student 51", rollno: "21AT1A0051", dob: "2002-04-24", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 52, name: "Student 52", rollno: "21AT1A0052", dob: "2002-05-25", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 53, name: "Student 53", rollno: "21AT1A0053", dob: "2002-06-26", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 54, name: "Student 54", rollno: "21AT1A0054", dob: "2002-07-27", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 55, name: "Student 55", rollno: "21AT1A0055", dob: "2002-08-28", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 56, name: "Student 56", rollno: "21AT1A0056", dob: "2002-09-01", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 57, name: "Student 57", rollno: "21AT1A0057", dob: "2002-10-02", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 58, name: "Student 58", rollno: "21AT1A0058", dob: "2002-11-03", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 59, name: "Student 59", rollno: "21AT1A0059", dob: "2002-12-04", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 60, name: "Student 60", rollno: "21AT1A0060", dob: "2002-01-05", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 61, name: "Student 61", rollno: "21AT1A0061", dob: "2002-02-06", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 62, name: "Student 62", rollno: "21AT1A0062", dob: "2002-03-07", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 63, name: "Student 63", rollno: "21AT1A0063", dob: "2002-04-08", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 64, name: "Student 64", rollno: "21AT1A0064", dob: "2002-05-09", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 65, name: "Student 65", rollno: "21AT1A0065", dob: "2002-06-10", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 66, name: "Student 66", rollno: "21AT1A0066", dob: "2002-07-11", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 67, name: "Student 67", rollno: "21AT1A0067", dob: "2002-08-12", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 68, name: "Student 68", rollno: "21AT1A0068", dob: "2002-09-13", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 69, name: "Student 69", rollno: "21AT1A0069", dob: "2002-10-14", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 70, name: "Student 70", rollno: "21AT1A0070", dob: "2002-11-15", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 71, name: "Student 71", rollno: "21AT1A0071", dob: "2002-12-16", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 72, name: "Student 72", rollno: "21AT1A0072", dob: "2002-01-17", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 73, name: "Student 73", rollno: "21AT1A0073", dob: "2002-02-18", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 74, name: "Student 74", rollno: "21AT1A0074", dob: "2002-03-19", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 75, name: "Student 75", rollno: "21AT1A0075", dob: "2002-04-20", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 76, name: "Student 76", rollno: "21AT1A0076", dob: "2002-05-21", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 77, name: "Student 77", rollno: "21AT1A0077", dob: "2002-06-22", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 78, name: "Student 78", rollno: "21AT1A0078", dob: "2002-07-23", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 79, name: "Student 79", rollno: "21AT1A0079", dob: "2002-08-24", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 80, name: "Student 80", rollno: "21AT1A0080", dob: "2002-09-25", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 81, name: "Student 81", rollno: "21AT1A0081", dob: "2002-10-26", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 82, name: "Student 82", rollno: "21AT1A0082", dob: "2002-11-27", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 83, name: "Student 83", rollno: "21AT1A0083", dob: "2002-12-28", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 84, name: "Student 84", rollno: "21AT1A0084", dob: "2002-01-01", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 85, name: "Student 85", rollno: "21AT1A0085", dob: "2002-02-02", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 86, name: "Student 86", rollno: "21AT1A0086", dob: "2002-03-03", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 87, name: "Student 87", rollno: "21AT1A0087", dob: "2002-04-04", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 88, name: "Student 88", rollno: "21AT1A0088", dob: "2002-05-05", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 89, name: "Student 89", rollno: "21AT1A0089", dob: "2002-06-06", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 90, name: "Student 90", rollno: "21AT1A0090", dob: "2002-07-07", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 91, name: "Student 91", rollno: "21AT1A0091", dob: "2002-08-08", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 92, name: "Student 92", rollno: "21AT1A0092", dob: "2002-09-09", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 93, name: "Student 93", rollno: "21AT1A0093", dob: "2002-10-10", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 94, name: "Student 94", rollno: "21AT1A0094", dob: "2002-11-11", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 95, name: "Student 95", rollno: "21AT1A0095", dob: "2002-12-12", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 96, name: "Student 96", rollno: "21AT1A0096", dob: "2002-01-13", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 97, name: "Student 97", rollno: "21AT1A0097", dob: "2002-02-14", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 98, name: "Student 98", rollno: "21AT1A0098", dob: "2002-03-15", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 99, name: "Student 99", rollno: "21AT1A0099", dob: "2002-04-16", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 100, name: "Student 100", rollno: "21AT1A0100", dob: "2002-05-17", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 101, name: "Student 101", rollno: "21AT1A0101", dob: "2002-06-18", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 102, name: "Student 102", rollno: "21AT1A0102", dob: "2002-07-19", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 103, name: "Student 103", rollno: "21AT1A0103", dob: "2002-08-20", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 104, name: "Student 104", rollno: "21AT1A0104", dob: "2002-09-21", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 105, name: "Student 105", rollno: "21AT1A0105", dob: "2002-10-22", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 106, name: "Student 106", rollno: "21AT1A0106", dob: "2002-11-23", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 107, name: "Student 107", rollno: "21AT1A0107", dob: "2002-12-24", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 108, name: "Student 108", rollno: "21AT1A0108", dob: "2002-01-25", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 109, name: "Student 109", rollno: "21AT1A0109", dob: "2002-02-26", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 110, name: "Student 110", rollno: "21AT1A0110", dob: "2002-03-27", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 111, name: "Student 111", rollno: "21AT1A0111", dob: "2002-04-28", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 112, name: "Student 112", rollno: "21AT1A0112", dob: "2002-05-01", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 113, name: "Student 113", rollno: "21AT1A0113", dob: "2002-06-02", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 114, name: "Student 114", rollno: "21AT1A0114", dob: "2002-07-03", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 115, name: "Student 115", rollno: "21AT1A0115", dob: "2002-08-04", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 116, name: "Student 116", rollno: "21AT1A0116", dob: "2002-09-05", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 117, name: "Student 117", rollno: "21AT1A0117", dob: "2002-10-06", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 118, name: "Student 118", rollno: "21AT1A0118", dob: "2002-11-07", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 119, name: "Student 119", rollno: "21AT1A0119", dob: "2002-12-08", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 120, name: "Student 120", rollno: "21AT1A0120", dob: "2002-01-09", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 121, name: "Student 121", rollno: "21AT1A0121", dob: "2002-02-10", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 122, name: "Student 122", rollno: "21AT1A0122", dob: "2002-03-11", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 123, name: "Student 123", rollno: "21AT1A0123", dob: "2002-04-12", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 124, name: "Student 124", rollno: "21AT1A0124", dob: "2002-05-13", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 125, name: "Student 125", rollno: "21AT1A0125", dob: "2002-06-14", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 126, name: "Student 126", rollno: "21AT1A0126", dob: "2002-07-15", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 127, name: "Student 127", rollno: "21AT1A0127", dob: "2002-08-16", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 128, name: "Student 128", rollno: "21AT1A0128", dob: "2002-09-17", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 129, name: "Student 129", rollno: "21AT1A0129", dob: "2002-10-18", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 130, name: "Student 130", rollno: "21AT1A0130", dob: "2002-11-19", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 131, name: "Student 131", rollno: "21AT1A0131", dob: "2002-12-20", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 132, name: "Student 132", rollno: "21AT1A0132", dob: "2002-01-21", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 133, name: "Student 133", rollno: "21AT1A0133", dob: "2002-02-22", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 134, name: "Student 134", rollno: "21AT1A0134", dob: "2002-03-23", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 135, name: "Student 135", rollno: "21AT1A0135", dob: "2002-04-24", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 136, name: "Student 136", rollno: "21AT1A0136", dob: "2002-05-25", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 137, name: "Student 137", rollno: "21AT1A0137", dob: "2002-06-26", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 138, name: "Student 138", rollno: "21AT1A0138", dob: "2002-07-27", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 139, name: "Student 139", rollno: "21AT1A0139", dob: "2002-08-28", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 140, name: "Student 140", rollno: "21AT1A0140", dob: "2002-09-01", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 141, name: "Student 141", rollno: "21AT1A0141", dob: "2002-10-02", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 142, name: "Student 142", rollno: "21AT1A0142", dob: "2002-11-03", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 143, name: "Student 143", rollno: "21AT1A0143", dob: "2002-12-04", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 144, name: "Student 144", rollno: "21AT1A0144", dob: "2002-01-05", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 145, name: "Student 145", rollno: "21AT1A0145", dob: "2002-02-06", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        { id: 146, name: "Student 146", rollno: "21AT1A0146", dob: "2002-03-07", dept: "ECE", address: "Anantapur", interests: ['Football', 'Music', 'Writing'] },
        { id: 147, name: "Student 147", rollno: "21AT1A0147", dob: "2002-04-08", dept: "EEE", address: "Bangalore", interests: ['Robotics', 'Reading', 'Photography'] },
        { id: 148, name: "Student 148", rollno: "21AT1A0148", dob: "2002-05-09", dept: "MECH", address: "Hyderabad", interests: ['Cricket', 'Dancing', 'Cooking'] },
        { id: 149, name: "Student 149", rollno: "21AT1A0149", dob: "2002-06-10", dept: "CIVIL", address: "Chennai", interests: ['Chess', 'Singing', 'Travel'] },
        { id: 150, name: "Student 150", rollno: "21AT1A0150", dob: "2002-07-11", dept: "CSE", address: "Tadipatri", interests: ['Gaming', 'Movies', 'Swimming'] },
        {
            id: 151,
            name: "Student 151",
            rollno: "21AT1A0151",
            dob: "2001-10-02",
            dept: "CSE",
            address: "Guntur",
            interests: ['Movies', 'Coding', 'Reading', 'Singing'],
          },
          {
            id: 152,
            name: "Student 152",
            rollno: "21AT1A0152",
            dob: "2003-03-11",
            dept: "EEE",
            address: "Hyderabad",
            interests: ['Swimming', 'Singing', 'Cricket', 'Traveling'],
          },
          {
            id: 153,
            name: "Student 153",
            rollno: "21AT1A0153",
            dob: "2003-09-18",
            dept: "IT",
            address: "Kurnool",
            interests: ['Drawing', 'Gaming', 'Reading', 'Movies'],
          },
          {
            id: 154,
            name: "Student 154",
            rollno: "21AT1A0154",
            dob: "2001-08-23",
            dept: "EEE",
            address: "Hyderabad",
            interests: ['Singing', 'Movies', 'Dancing', 'Swimming'],
          },
          {
            id: 155,
            name: "Student 155",
            rollno: "21AT1A0155",
            dob: "2003-10-03",
            dept: "CSE",
            address: "Kadapa",
            interests: ['Coding', 'Movies', 'Singing', 'Gaming'],
          },
          {
            id: 156,
            name: "Student 156",
            rollno: "21AT1A0156",
            dob: "2002-04-16",
            dept: "IT",
            address: "Guntur",
            interests: ['Drawing', 'Movies', 'Singing'],
          },
          {
            id: 157,
            name: "Student 157",
            rollno: "21AT1A0157",
            dob: "2002-05-27",
            dept: "ECE",
            address: "Kadapa",
            interests: ['Traveling', 'Coding', 'Singing'],
          },
          {
            id: 158,
            name: "Student 158",
            rollno: "21AT1A0158",
            dob: "2002-07-16",
            dept: "CIVIL",
            address: "Kadapa",
            interests: ['Singing', 'Drawing', 'Dancing'],
          },
          {
            id: 159,
            name: "Student 159",
            rollno: "21AT1A0159",
            dob: "2003-05-02",
            dept: "MECH",
            address: "Anantapur",
            interests: ['Gaming', 'Cricket', 'Movies', 'Singing'],
          },
          {
            id: 160,
            name: "Student 160",
            rollno: "21AT1A0160",
            dob: "2001-04-18",
            dept: "CIVIL",
            address: "Kadapa",
            interests: ['Dancing', 'Coding'],
          },
          {
            id: 161,
            name: "Student 161",
            rollno: "21AT1A0161",
            dob: "2001-02-10",
            dept: "ECE",
            address: "Nellore",
            interests: ['Cricket', 'Gaming'],
          },
          {
            id: 162,
            name: "Student 162",
            rollno: "21AT1A0162",
            dob: "2002-11-23",
            dept: "MECH",
            address: "Tadipatri",
            interests: ['Swimming', 'Dancing', 'Singing', 'Traveling'],
          },
          {
            id: 163,
            name: "Student 163",
            rollno: "21AT1A0163",
            dob: "2003-01-09",
            dept: "MECH",
            address: "Chittoor",
            interests: ['Singing', 'Reading', 'Traveling'],
          },
          {
            id: 164,
            name: "Student 164",
            rollno: "21AT1A0164",
            dob: "2002-09-17",
            dept: "IT",
            address: "Vijayawada",
            interests: ['Gaming', 'Traveling'],
          },
          {
            id: 165,
            name: "Student 165",
            rollno: "21AT1A0165",
            dob: "2003-11-11",
            dept: "CSE",
            address: "Tadipatri",
            interests: ['Reading', 'Drawing', 'Movies', 'Coding'],
          },
          {
            id: 166,
            name: "Student 166",
            rollno: "21AT1A0166",
            dob: "2001-05-06",
            dept: "CSE",
            address: "Nellore",
            interests: ['Cricket', 'Coding', 'Swimming'],
          },
          {
            id: 167,
            name: "Student 167",
            rollno: "21AT1A0167",
            dob: "2002-03-08",
            dept: "EEE",
            address: "Anantapur",
            interests: ['Singing', 'Movies', 'Cricket', 'Gaming'],
          },
          {
            id: 168,
            name: "Student 168",
            rollno: "21AT1A0168",
            dob: "2002-05-15",
            dept: "ECE",
            address: "Hyderabad",
            interests: ['Reading', 'Cricket'],
          },
          {
            id: 169,
            name: "Student 169",
            rollno: "21AT1A0169",
            dob: "2003-08-05",
            dept: "IT",
            address: "Kurnool",
            interests: ['Reading', 'Coding', 'Traveling'],
          },
          {
            id: 170,
            name: "Student 170",
            rollno: "21AT1A0170",
            dob: "2001-07-30",
            dept: "CSE",
            address: "Vizag",
            interests: ['Drawing', 'Cricket'],
          },
          {
            id: 171,
            name: "Student 171",
            rollno: "21AT1A0171",
            dob: "2003-08-02",
            dept: "IT",
            address: "Hyderabad",
            interests: ['Movies', 'Coding', 'Cricket', 'Drawing'],
          },
          {
            id: 172,
            name: "Student 172",
            rollno: "21AT1A0172",
            dob: "2002-09-12",
            dept: "EEE",
            address: "Tadipatri",
            interests: ['Dancing', 'Drawing', 'Cricket', 'Movies'],
          },
          {
            id: 173,
            name: "Student 173",
            rollno: "21AT1A0173",
            dob: "2001-09-22",
            dept: "CSE",
            address: "Vizag",
            interests: ['Gaming', 'Reading', 'Swimming', 'Traveling'],
          },
          {
            id: 174,
            name: "Student 174",
            rollno: "21AT1A0174",
            dob: "2002-03-25",
            dept: "MECH",
            address: "Tadipatri",
            interests: ['Dancing', 'Gaming', 'Drawing', 'Movies'],
          },
          {
            id: 175,
            name: "Student 175",
            rollno: "21AT1A0175",
            dob: "2003-10-01",
            dept: "IT",
            address: "Tadipatri",
            interests: ['Traveling', 'Drawing', 'Swimming'],
          },
          {
            id: 176,
            name: "Student 176",
            rollno: "21AT1A0176",
            dob: "2001-10-22",
            dept: "EEE",
            address: "Kurnool",
            interests: ['Gaming', 'Drawing'],
          },
          {
            id: 177,
            name: "Student 177",
            rollno: "21AT1A0177",
            dob: "2002-07-14",
            dept: "CIVIL",
            address: "Chittoor",
            interests: ['Dancing', 'Coding', 'Drawing', 'Singing'],
          },
          {
            id: 178,
            name: "Student 178",
            rollno: "21AT1A0178",
            dob: "2002-01-06",
            dept: "CIVIL",
            address: "Kadapa",
            interests: ['Movies', 'Reading', 'Swimming'],
          },
          {
            id: 179,
            name: "Student 179",
            rollno: "21AT1A0179",
            dob: "2001-09-26",
            dept: "CIVIL",
            address: "Vijayawada",
            interests: ['Singing', 'Drawing'],
          },
          {
            id: 180,
            name: "Student 180",
            rollno: "21AT1A0180",
            dob: "2003-11-06",
            dept: "EEE",
            address: "Kurnool",
            interests: ['Reading', 'Traveling', 'Movies', 'Singing'],
          },
          {
            id: 181,
            name: "Student 181",
            rollno: "21AT1A0181",
            dob: "2003-04-17",
            dept: "CSE",
            address: "Kadapa",
            interests: ['Traveling', 'Movies'],
          },
          {
            id: 182,
            name: "Student 182",
            rollno: "21AT1A0182",
            dob: "2002-06-08",
            dept: "CIVIL",
            address: "Kadapa",
            interests: ['Drawing', 'Traveling', 'Cricket'],
          },
          {
            id: 183,
            name: "Student 183",
            rollno: "21AT1A0183",
            dob: "2002-05-04",
            dept: "CIVIL",
            address: "Kadapa",
            interests: ['Dancing', 'Swimming', 'Drawing'],
          },
          {
            id: 184,
            name: "Student 184",
            rollno: "21AT1A0184",
            dob: "2001-01-09",
            dept: "MECH",
            address: "Nellore",
            interests: ['Coding', 'Dancing'],
          },
          {
            id: 185,
            name: "Student 185",
            rollno: "21AT1A0185",
            dob: "2003-10-11",
            dept: "CSE",
            address: "Tadipatri",
            interests: ['Traveling', 'Swimming', 'Gaming', 'Drawing'],
          },
          {
            id: 186,
            name: "Student 186",
            rollno: "21AT1A0186",
            dob: "2003-12-09",
            dept: "EEE",
            address: "Vizag",
            interests: ['Dancing', 'Cricket', 'Coding'],
          },
          {
            id: 187,
            name: "Student 187",
            rollno: "21AT1A0187",
            dob: "2001-01-21",
            dept: "EEE",
            address: "Anantapur",
            interests: ['Drawing', 'Singing', 'Traveling', 'Movies'],
          },
          {
            id: 188,
            name: "Student 188",
            rollno: "21AT1A0188",
            dob: "2003-09-30",
            dept: "IT",
            address: "Kadapa",
            interests: ['Drawing', 'Reading', 'Gaming'],
          },
          {
            id: 189,
            name: "Student 189",
            rollno: "21AT1A0189",
            dob: "2001-06-10",
            dept: "IT",
            address: "Chittoor",
            interests: ['Drawing', 'Traveling'],
          },
          {
            id: 190,
            name: "Student 190",
            rollno: "21AT1A0190",
            dob: "2002-10-15",
            dept: "EEE",
            address: "Guntur",
            interests: ['Cricket', 'Singing'],
          },
          {
            id: 191,
            name: "Student 191",
            rollno: "21AT1A0191",
            dob: "2003-04-07",
            dept: "IT",
            address: "Guntur",
            interests: ['Gaming', 'Drawing'],
          },
          {
            id: 192,
            name: "Student 192",
            rollno: "21AT1A0192",
            dob: "2002-12-24",
            dept: "CSE",
            address: "Vizag",
            interests: ['Singing', 'Reading', 'Gaming'],
          },
          {
            id: 193,
            name: "Student 193",
            rollno: "21AT1A0193",
            dob: "2002-08-24",
            dept: "MECH",
            address: "Nellore",
            interests: ['Dancing', 'Singing', 'Traveling'],
          },
          {
            id: 194,
            name: "Student 194",
            rollno: "21AT1A0194",
            dob: "2002-11-19",
            dept: "ECE",
            address: "Tadipatri",
            interests: ['Traveling', 'Movies'],
          },
          {
            id: 195,
            name: "Student 195",
            rollno: "21AT1A0195",
            dob: "2002-03-24",
            dept: "CSE",
            address: "Vizag",
            interests: ['Singing', 'Reading', 'Movies', 'Dancing'],
          },
          {
            id: 196,
            name: "Student 196",
            rollno: "21AT1A0196",
            dob: "2003-12-24",
            dept: "CIVIL",
            address: "Kadapa",
            interests: ['Singing', 'Cricket'],
          },
          {
            id: 197,
            name: "Student 197",
            rollno: "21AT1A0197",
            dob: "2003-06-24",
            dept: "EEE",
            address: "Guntur",
            interests: ['Movies', 'Drawing', 'Gaming', 'Swimming'],
          },
          {
            id: 198,
            name: "Student 198",
            rollno: "21AT1A0198",
            dob: "2002-09-15",
            dept: "ECE",
            address: "Vijayawada",
            interests: ['Swimming', 'Movies'],
          },
          {
            id: 199,
            name: "Student 199",
            rollno: "21AT1A0199",
            dob: "2001-02-23",
            dept: "IT",
            address: "Chittoor",
            interests: ['Gaming', 'Coding'],
          },
          {
            id: 200,
            name: "Student 200",
            rollno: "21AT1A0200",
            dob: "2001-01-26",
            dept: "CIVIL",
            address: "Vizag",
            interests: ['Dancing', 'Traveling'],
          },
          {
            id: 201,
            name: "Student 201",
            rollno: "21AT1A0201",
            dob: "2003-08-15",
            dept: "CIVIL",
            address: "Vizag",
            interests: ['Drawing', 'Dancing'],
          },
          {
            id: 202,
            name: "Student 202",
            rollno: "21AT1A0202",
            dob: "2003-09-22",
            dept: "ECE",
            address: "Vijayawada",
            interests: ['Singing', 'Swimming', 'Cricket'],
          },
          {
            id: 203,
            name: "Student 203",
            rollno: "21AT1A0203",
            dob: "2003-05-20",
            dept: "IT",
            address: "Chittoor",
            interests: ['Drawing', 'Singing', 'Coding'],
          },
          {
            id: 204,
            name: "Student 204",
            rollno: "21AT1A0204",
            dob: "2002-10-14",
            dept: "CSE",
            address: "Nellore",
            interests: ['Reading', 'Cricket', 'Gaming'],
          },
          {
            id: 205,
            name: "Student 205",
            rollno: "21AT1A0205",
            dob: "2002-08-31",
            dept: "ECE",
            address: "Tadipatri",
            interests: ['Coding', 'Gaming', 'Singing'],
          },
          {
            id: 206,
            name: "Student 206",
            rollno: "21AT1A0206",
            dob: "2002-12-25",
            dept: "EEE",
            address: "Kurnool",
            interests: ['Movies', 'Dancing', 'Reading'],
          },
          {
            id: 207,
            name: "Student 207",
            rollno: "21AT1A0207",
            dob: "2001-02-12",
            dept: "ECE",
            address: "Tadipatri",
            interests: ['Dancing', 'Drawing', 'Singing'],
          },
          {
            id: 208,
            name: "Student 208",
            rollno: "21AT1A0208",
            dob: "2003-03-21",
            dept: "EEE",
            address: "Tadipatri",
            interests: ['Reading', 'Dancing', 'Coding', 'Gaming'],
          },
          {
            id: 209,
            name: "Student 209",
            rollno: "21AT1A0209",
            dob: "2001-02-17",
            dept: "ECE",
            address: "Nellore",
            interests: ['Coding', 'Singing'],
          },
          {
            id: 210,
            name: "Student 210",
            rollno: "21AT1A0210",
            dob: "2001-12-22",
            dept: "CIVIL",
            address: "Hyderabad",
            interests: ['Reading', 'Drawing'],
          },
          {
            id: 211,
            name: "Student 211",
            rollno: "21AT1A0211",
            dob: "2001-05-30",
            dept: "ECE",
            address: "Anantapur",
            interests: ['Coding', 'Movies', 'Swimming', 'Reading'],
          },
          {
            id: 212,
            name: "Student 212",
            rollno: "21AT1A0212",
            dob: "2002-02-17",
            dept: "IT",
            address: "Kadapa",
            interests: ['Reading', 'Dancing'],
          },
          {
            id: 213,
            name: "Student 213",
            rollno: "21AT1A0213",
            dob: "2002-09-15",
            dept: "ECE",
            address: "Nellore",
            interests: ['Reading', 'Coding', 'Swimming', 'Traveling'],
          },
          {
            id: 214,
            name: "Student 214",
            rollno: "21AT1A0214",
            dob: "2002-03-19",
            dept: "IT",
            address: "Nellore",
            interests: ['Gaming', 'Reading', 'Coding'],
          },
          {
            id: 215,
            name: "Student 215",
            rollno: "21AT1A0215",
            dob: "2002-05-03",
            dept: "EEE",
            address: "Nellore",
            interests: ['Movies', 'Dancing', 'Swimming'],
          },
          {
            id: 216,
            name: "Student 216",
            rollno: "21AT1A0216",
            dob: "2001-10-21",
            dept: "CSE",
            address: "Tadipatri",
            interests: ['Reading', 'Dancing', 'Gaming'],
          },
          {
            id: 217,
            name: "Student 217",
            rollno: "21AT1A0217",
            dob: "2001-02-06",
            dept: "IT",
            address: "Kadapa",
            interests: ['Movies', 'Gaming'],
          },
          {
            id: 218,
            name: "Student 218",
            rollno: "21AT1A0218",
            dob: "2003-04-11",
            dept: "EEE",
            address: "Chittoor",
            interests: ['Singing', 'Cricket', 'Drawing'],
          },
          {
            id: 219,
            name: "Student 219",
            rollno: "21AT1A0219",
            dob: "2002-08-02",
            dept: "CSE",
            address: "Kadapa",
            interests: ['Movies', 'Drawing', 'Reading'],
          },
          {
            id: 220,
            name: "Student 220",
            rollno: "21AT1A0220",
            dob: "2003-01-09",
            dept: "CSE",
            address: "Vijayawada",
            interests: ['Traveling', 'Movies', 'Cricket'],
          },
          {
            id: 221,
            name: "Student 221",
            rollno: "21AT1A0221",
            dob: "2002-02-01",
            dept: "MECH",
            address: "Hyderabad",
            interests: ['Coding', 'Gaming', 'Drawing', 'Cricket'],
          },
          {
            id: 222,
            name: "Student 222",
            rollno: "21AT1A0222",
            dob: "2002-06-23",
            dept: "CSE",
            address: "Guntur",
            interests: ['Reading', 'Coding', 'Traveling'],
          },
          {
            id: 223,
            name: "Student 223",
            rollno: "21AT1A0223",
            dob: "2003-06-15",
            dept: "ECE",
            address: "Vizag",
            interests: ['Cricket', 'Reading', 'Coding', 'Dancing'],
          },
          {
            id: 224,
            name: "Student 224",
            rollno: "21AT1A0224",
            dob: "2003-06-07",
            dept: "MECH",
            address: "Nellore",
            interests: ['Swimming', 'Dancing', 'Movies'],
          },
          {
            id: 225,
            name: "Student 225",
            rollno: "21AT1A0225",
            dob: "2001-06-19",
            dept: "CSE",
            address: "Vijayawada",
            interests: ['Reading', 'Coding', 'Gaming', 'Traveling'],
          },
          {
            id: 226,
            name: "Student 226",
            rollno: "21AT1A0226",
            dob: "2003-03-14",
            dept: "IT",
            address: "Anantapur",
            interests: ['Dancing', 'Gaming', 'Movies'],
          },
          {
            id: 227,
            name: "Student 227",
            rollno: "21AT1A0227",
            dob: "2003-09-30",
            dept: "EEE",
            address: "Chittoor",
            interests: ['Swimming', 'Coding', 'Traveling'],
          },
          {
            id: 228,
            name: "Student 228",
            rollno: "21AT1A0228",
            dob: "2001-10-28",
            dept: "IT",
            address: "Anantapur",
            interests: ['Dancing', 'Traveling', 'Gaming', 'Coding'],
          },
          {
            id: 229,
            name: "Student 229",
            rollno: "21AT1A0229",
            dob: "2001-04-02",
            dept: "EEE",
            address: "Anantapur",
            interests: ['Drawing', 'Singing', 'Coding'],
          },
          {
            id: 230,
            name: "Student 230",
            rollno: "21AT1A0230",
            dob: "2003-04-13",
            dept: "CSE",
            address: "Vizag",
            interests: ['Swimming', 'Gaming'],
          },
          {
            id: 231,
            name: "Student 231",
            rollno: "21AT1A0231",
            dob: "2002-04-30",
            dept: "ECE",
            address: "Guntur",
            interests: ['Movies', 'Swimming'],
          },
          {
            id: 232,
            name: "Student 232",
            rollno: "21AT1A0232",
            dob: "2002-05-23",
            dept: "EEE",
            address: "Nellore",
            interests: ['Drawing', 'Dancing'],
          },
          {
            id: 233,
            name: "Student 233",
            rollno: "21AT1A0233",
            dob: "2002-03-27",
            dept: "MECH",
            address: "Guntur",
            interests: ['Dancing', 'Singing', 'Swimming', 'Drawing'],
          },
          {
            id: 234,
            name: "Student 234",
            rollno: "21AT1A0234",
            dob: "2002-10-05",
            dept: "IT",
            address: "Tadipatri",
            interests: ['Coding', 'Movies'],
          },
          {
            id: 235,
            name: "Student 235",
            rollno: "21AT1A0235",
            dob: "2002-01-20",
            dept: "EEE",
            address: "Guntur",
            interests: ['Drawing', 'Movies', 'Singing', 'Reading'],
          },
          {
            id: 236,
            name: "Student 236",
            rollno: "21AT1A0236",
            dob: "2003-09-16",
            dept: "ECE",
            address: "Kadapa",
            interests: ['Movies', 'Cricket'],
          },
          {
            id: 237,
            name: "Student 237",
            rollno: "21AT1A0237",
            dob: "2002-11-12",
            dept: "MECH",
            address: "Hyderabad",
            interests: ['Dancing', 'Singing', 'Movies'],
          },
          {
            id: 238,
            name: "Student 238",
            rollno: "21AT1A0238",
            dob: "2002-04-16",
            dept: "IT",
            address: "Vijayawada",
            interests: ['Cricket', 'Gaming', 'Coding'],
          },
          {
            id: 239,
            name: "Student 239",
            rollno: "21AT1A0239",
            dob: "2002-11-10",
            dept: "CIVIL",
            address: "Vijayawada",
            interests: ['Dancing', 'Swimming'],
          },
          {
            id: 240,
            name: "Student 240",
            rollno: "21AT1A0240",
            dob: "2001-04-05",
            dept: "MECH",
            address: "Vijayawada",
            interests: ['Cricket', 'Movies'],
          },
          {
            id: 241,
            name: "Student 241",
            rollno: "21AT1A0241",
            dob: "2001-05-12",
            dept: "CIVIL",
            address: "Hyderabad",
            interests: ['Coding', 'Dancing'],
          },
          {
            id: 242,
            name: "Student 242",
            rollno: "21AT1A0242",
            dob: "2003-03-31",
            dept: "EEE",
            address: "Vijayawada",
            interests: ['Movies', 'Drawing'],
          },
          {
            id: 243,
            name: "Student 243",
            rollno: "21AT1A0243",
            dob: "2002-07-15",
            dept: "ECE",
            address: "Hyderabad",
            interests: ['Singing', 'Cricket', 'Swimming'],
          },
          {
            id: 244,
            name: "Student 244",
            rollno: "21AT1A0244",
            dob: "2001-04-14",
            dept: "IT",
            address: "Vijayawada",
            interests: ['Cricket', 'Movies', 'Dancing', 'Drawing'],
          },
          {
            id: 245,
            name: "Student 245",
            rollno: "21AT1A0245",
            dob: "2001-07-06",
            dept: "ECE",
            address: "Kadapa",
            interests: ['Gaming', 'Singing', 'Traveling', 'Drawing'],
          },
          {
            id: 246,
            name: "Student 246",
            rollno: "21AT1A0246",
            dob: "2001-11-21",
            dept: "ECE",
            address: "Nellore",
            interests: ['Traveling', 'Reading'],
          },
          {
            id: 247,
            name: "Student 247",
            rollno: "21AT1A0247",
            dob: "2002-08-07",
            dept: "MECH",
            address: "Vijayawada",
            interests: ['Swimming', 'Coding'],
          },
          {
            id: 248,
            name: "Student 248",
            rollno: "21AT1A0248",
            dob: "2003-04-18",
            dept: "CSE",
            address: "Tadipatri",
            interests: ['Coding', 'Cricket', 'Singing'],
          },
          {
            id: 249,
            name: "Student 249",
            rollno: "21AT1A0249",
            dob: "2001-10-18",
            dept: "IT",
            address: "Tadipatri",
            interests: ['Reading', 'Gaming', 'Cricket', 'Singing'],
          },
          {
            id: 250,
            name: "Student 250",
            rollno: "21AT1A0250",
            dob: "2003-10-09",
            dept: "CIVIL",
            address: "Guntur",
            interests: ['Gaming', 'Coding', 'Dancing'],
          },
          {
            id: 251,
            name: "Student 251",
            rollno: "21AT1A0251",
            dob: "2003-01-04",
            dept: "IT",
            address: "Tadipatri",
            interests: ['Traveling', 'Reading', 'Drawing'],
          },
          {
            id: 252,
            name: "Student 252",
            rollno: "21AT1A0252",
            dob: "2002-12-08",
            dept: "CIVIL",
            address: "Kadapa",
            interests: ['Swimming', 'Singing'],
          },
          {
            id: 253,
            name: "Student 253",
            rollno: "21AT1A0253",
            dob: "2001-08-10",
            dept: "MECH",
            address: "Anantapur",
            interests: ['Swimming', 'Coding'],
          },
          {
            id: 254,
            name: "Student 254",
            rollno: "21AT1A0254",
            dob: "2001-07-14",
            dept: "MECH",
            address: "Hyderabad",
            interests: ['Dancing', 'Singing'],
          },
          {
            id: 255,
            name: "Student 255",
            rollno: "21AT1A0255",
            dob: "2003-03-23",
            dept: "IT",
            address: "Chittoor",
            interests: ['Traveling', 'Drawing'],
          },
          {
            id: 256,
            name: "Student 256",
            rollno: "21AT1A0256",
            dob: "2002-02-18",
            dept: "ECE",
            address: "Vijayawada",
            interests: ['Traveling', 'Coding', 'Gaming'],
          },
          {
            id: 257,
            name: "Student 257",
            rollno: "21AT1A0257",
            dob: "2001-08-18",
            dept: "EEE",
            address: "Vizag",
            interests: ['Drawing', 'Cricket'],
          },
          {
            id: 258,
            name: "Student 258",
            rollno: "21AT1A0258",
            dob: "2001-04-10",
            dept: "MECH",
            address: "Vijayawada",
            interests: ['Cricket', 'Reading'],
          },
          {
            id: 259,
            name: "Student 259",
            rollno: "21AT1A0259",
            dob: "2001-06-01",
            dept: "MECH",
            address: "Guntur",
            interests: ['Movies', 'Gaming', 'Cricket'],
          },
          {
            id: 260,
            name: "Student 260",
            rollno: "21AT1A0260",
            dob: "2001-04-05",
            dept: "IT",
            address: "Kurnool",
            interests: ['Drawing', 'Gaming', 'Cricket'],
          },
          {
            id: 261,
            name: "Student 261",
            rollno: "21AT1A0261",
            dob: "2003-11-26",
            dept: "CSE",
            address: "Vijayawada",
            interests: ['Coding', 'Dancing', 'Movies', 'Singing'],
          },
          {
            id: 262,
            name: "Student 262",
            rollno: "21AT1A0262",
            dob: "2002-03-16",
            dept: "CSE",
            address: "Hyderabad",
            interests: ['Drawing', 'Cricket', 'Reading', 'Gaming'],
          },
          {
            id: 263,
            name: "Student 263",
            rollno: "21AT1A0263",
            dob: "2002-05-10",
            dept: "CIVIL",
            address: "Vijayawada",
            interests: ['Cricket', 'Drawing', 'Reading'],
          },
          {
            id: 264,
            name: "Student 264",
            rollno: "21AT1A0264",
            dob: "2001-05-09",
            dept: "CIVIL",
            address: "Nellore",
            interests: ['Swimming', 'Coding'],
          },
          {
            id: 265,
            name: "Student 265",
            rollno: "21AT1A0265",
            dob: "2003-05-11",
            dept: "IT",
            address: "Hyderabad",
            interests: ['Singing', 'Reading', 'Drawing', 'Movies'],
          },
          {
            id: 266,
            name: "Student 266",
            rollno: "21AT1A0266",
            dob: "2002-06-13",
            dept: "EEE",
            address: "Vijayawada",
            interests: ['Reading', 'Gaming', 'Singing', 'Dancing'],
          },
          {
            id: 267,
            name: "Student 267",
            rollno: "21AT1A0267",
            dob: "2001-10-26",
            dept: "MECH",
            address: "Nellore",
            interests: ['Coding', 'Swimming'],
          },
          {
            id: 268,
            name: "Student 268",
            rollno: "21AT1A0268",
            dob: "2001-02-07",
            dept: "ECE",
            address: "Kurnool",
            interests: ['Reading', 'Coding'],
          },
          {
            id: 269,
            name: "Student 269",
            rollno: "21AT1A0269",
            dob: "2002-04-24",
            dept: "CSE",
            address: "Chittoor",
            interests: ['Dancing', 'Cricket', 'Singing', 'Swimming'],
          },
          {
            id: 270,
            name: "Student 270",
            rollno: "21AT1A0270",
            dob: "2002-10-22",
            dept: "EEE",
            address: "Hyderabad",
            interests: ['Movies', 'Traveling'],
          },
          {
            id: 271,
            name: "Student 271",
            rollno: "21AT1A0271",
            dob: "2002-06-24",
            dept: "CSE",
            address: "Anantapur",
            interests: ['Coding', 'Dancing'],
          },
          {
            id: 272,
            name: "Student 272",
            rollno: "21AT1A0272",
            dob: "2003-05-02",
            dept: "ECE",
            address: "Hyderabad",
            interests: ['Reading', 'Traveling', 'Cricket'],
          },
          {
            id: 273,
            name: "Student 273",
            rollno: "21AT1A0273",
            dob: "2002-04-26",
            dept: "MECH",
            address: "Kadapa",
            interests: ['Coding', 'Gaming'],
          },
          {
            id: 274,
            name: "Student 274",
            rollno: "21AT1A0274",
            dob: "2003-12-24",
            dept: "CSE",
            address: "Kadapa",
            interests: ['Drawing', 'Traveling', 'Dancing', 'Movies'],
          },
          {
            id: 275,
            name: "Student 275",
            rollno: "21AT1A0275",
            dob: "2003-01-28",
            dept: "CIVIL",
            address: "Guntur",
            interests: ['Gaming', 'Reading'],
          },
          {
            id: 276,
            name: "Student 276",
            rollno: "21AT1A0276",
            dob: "2003-08-19",
            dept: "MECH",
            address: "Kurnool",
            interests: ['Coding', 'Cricket', 'Singing'],
          },
          {
            id: 277,
            name: "Student 277",
            rollno: "21AT1A0277",
            dob: "2001-01-29",
            dept: "EEE",
            address: "Hyderabad",
            interests: ['Singing', 'Movies', 'Drawing', 'Reading'],
          },
          {
            id: 278,
            name: "Student 278",
            rollno: "21AT1A0278",
            dob: "2001-08-13",
            dept: "MECH",
            address: "Tadipatri",
            interests: ['Coding', 'Swimming'],
          },
          {
            id: 279,
            name: "Student 279",
            rollno: "21AT1A0279",
            dob: "2001-06-30",
            dept: "EEE",
            address: "Kurnool",
            interests: ['Traveling', 'Singing', 'Drawing', 'Dancing'],
          },
          {
            id: 280,
            name: "Student 280",
            rollno: "21AT1A0280",
            dob: "2001-01-24",
            dept: "CSE",
            address: "Guntur",
            interests: ['Drawing', 'Movies', 'Dancing'],
          },
          {
            id: 281,
            name: "Student 281",
            rollno: "21AT1A0281",
            dob: "2001-09-15",
            dept: "EEE",
            address: "Chittoor",
            interests: ['Reading', 'Movies'],
          },
          {
            id: 282,
            name: "Student 282",
            rollno: "21AT1A0282",
            dob: "2001-02-27",
            dept: "MECH",
            address: "Vizag",
            interests: ['Drawing', 'Gaming'],
          },
          {
            id: 283,
            name: "Student 283",
            rollno: "21AT1A0283",
            dob: "2002-10-10",
            dept: "CIVIL",
            address: "Guntur",
            interests: ['Dancing', 'Traveling', 'Swimming', 'Cricket'],
          },
          {
            id: 284,
            name: "Student 284",
            rollno: "21AT1A0284",
            dob: "2002-05-10",
            dept: "MECH",
            address: "Guntur",
            interests: ['Gaming', 'Traveling', 'Cricket'],
          },
          {
            id: 285,
            name: "Student 285",
            rollno: "21AT1A0285",
            dob: "2003-11-04",
            dept: "CSE",
            address: "Tadipatri",
            interests: ['Coding', 'Movies'],
          },
          {
            id: 286,
            name: "Student 286",
            rollno: "21AT1A0286",
            dob: "2003-11-04",
            dept: "MECH",
            address: "Chittoor",
            interests: ['Movies', 'Gaming', 'Cricket', 'Coding'],
          },
          {
            id: 287,
            name: "Student 287",
            rollno: "21AT1A0287",
            dob: "2002-02-22",
            dept: "MECH",
            address: "Chittoor",
            interests: ['Reading', 'Movies'],
          },
          {
            id: 288,
            name: "Student 288",
            rollno: "21AT1A0288",
            dob: "2002-12-04",
            dept: "CSE",
            address: "Guntur",
            interests: ['Traveling', 'Swimming'],
          },
          {
            id: 289,
            name: "Student 289",
            rollno: "21AT1A0289",
            dob: "2001-01-22",
            dept: "CSE",
            address: "Guntur",
            interests: ['Reading', 'Gaming'],
          },
          {
            id: 290,
            name: "Student 290",
            rollno: "21AT1A0290",
            dob: "2002-07-01",
            dept: "ECE",
            address: "Tadipatri",
            interests: ['Traveling', 'Dancing', 'Coding'],
          },
          {
            id: 291,
            name: "Student 291",
            rollno: "21AT1A0291",
            dob: "2002-09-15",
            dept: "CIVIL",
            address: "Vizag",
            interests: ['Reading', 'Dancing'],
          },
          {
            id: 292,
            name: "Student 292",
            rollno: "21AT1A0292",
            dob: "2003-04-09",
            dept: "EEE",
            address: "Nellore",
            interests: ['Movies', 'Cricket', 'Singing', 'Traveling'],
          },
          {
            id: 293,
            name: "Student 293",
            rollno: "21AT1A0293",
            dob: "2003-03-12",
            dept: "EEE",
            address: "Anantapur",
            interests: ['Drawing', 'Swimming', 'Dancing'],
          },
          {
            id: 294,
            name: "Student 294",
            rollno: "21AT1A0294",
            dob: "2003-06-29",
            dept: "ECE",
            address: "Kurnool",
            interests: ['Traveling', 'Movies', 'Singing'],
          },
          {
            id: 295,
            name: "Student 295",
            rollno: "21AT1A0295",
            dob: "2002-07-15",
            dept: "CIVIL",
            address: "Hyderabad",
            interests: ['Coding', 'Traveling'],
          },
          {
            id: 296,
            name: "Student 296",
            rollno: "21AT1A0296",
            dob: "2003-12-23",
            dept: "CIVIL",
            address: "Guntur",
            interests: ['Gaming', 'Coding', 'Traveling', 'Movies'],
          },
          {
            id: 297,
            name: "Student 297",
            rollno: "21AT1A0297",
            dob: "2003-07-02",
            dept: "IT",
            address: "Kadapa",
            interests: ['Drawing', 'Reading', 'Coding'],
          },
          {
            id: 298,
            name: "Student 298",
            rollno: "21AT1A0298",
            dob: "2002-07-17",
            dept: "CIVIL",
            address: "Kurnool",
            interests: ['Drawing', 'Swimming'],
          },
          {
            id: 299,
            name: "Student 299",
            rollno: "21AT1A0299",
            dob: "2001-02-03",
            dept: "MECH",
            address: "Tadipatri",
            interests: ['Drawing', 'Swimming', 'Gaming'],
          },
          {
            id: 300,
            name: "Student 300",
            rollno: "21AT1A0300",
            dob: "2003-05-26",
            dept: "CSE",
            address: "Chittoor",
            interests: ['Movies', 'Dancing', 'Coding', 'Traveling'],
          },
    ]
}
